version: '2'
services:
  test:
    build: .
    depends_on:
      - broker0
      - broker1
    volumes:
      - ./lib:/srv/kafkaesq/lib
      - ./test:/srv/kafkaesq/test
      - ./dev:/srv/kafkaesq/dev
      - ./package.json:/srv/kafkaesq/package.json
      - ./.eslintrc.json:/srv/kafkaesq/.eslintrc.json

  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - 2181:2181

  broker0:
    image: ches/kafka:0.10.0.1
    volumes:
      - ./brokers/broker0/data:/data
      - ./brokers/broker0/logs:/logs
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=broker0
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_BROKER_ID=0
    depends_on:
      - zookeeper

  broker1:
    image: ches/kafka:0.10.0.1
    ports:
      - 9093:9092
    volumes:
      - ./brokers/broker1/data:/data
      - ./brokers/broker1/logs:/logs
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=broker1
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper
