version: '2'
services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: ches/kafka:0.10.0.1
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - ZOOKEEPER_IP=zookeeper
    depends_on:
      - zookeeper
