version: '2'
services:
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - 2181:2181

  broker_0:
    image: ches/kafka:0.10.0.1
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_BROKER_ID=0
    depends_on:
      - zookeeper

  broker_1:
    image: ches/kafka:0.10.0.1
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=broker
      - ZOOKEEPER_IP=zookeeper
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper
